import React from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { AiFillFacebook, AiFillGithub} from "react-icons/ai";
import { Footer } from '../components/Footer';
import { Header } from '../components/Header';
import { ButtonContact } from '../components/Button';
import { ButtonChat } from '../components/Button/ButtonChat';
import Link from 'next/link';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Marcos Vini</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

          <div className={styles.content}>

            <Header />
              
              <div className={styles.signSocial}>
                <Link  href="https://www.facebook.com/colabdevs-106903418296797" >
                  <a target="_blank" > Facebook </a>
                </Link>

                <Link href="https://www.instagram.com/colabdevs/">
                  <a target="_blank"> Instagram  </a>
                </Link>
                
                <Link href="https://www.youtube.com/channel/UCGhZ5sH2SbSjMQ7edb7Cb_g" >
                  <a target="_blank"> Youtube </a>
                </Link>
                
                <Link  href="https://www.linkedin.com/in/colab-devs-7b41b3244/">
                  <a target="_blank"> Linkdin </a>
                </Link>
                
              
              </div>

            
            
              <ButtonChat />
            
            
          </div>

      </main>

           
    </div>
  );
};


